name: Security Misconfiguration Vulnerability Test
description: Test for misconfiguration issues, such as access to sensitive files.
severity: High
author: Project
tags:
  - misconfiguration
  - security
http:
  - method: GET
    path:
      - "{{BaseURL}}/.env"
    headers:
      User-Agent: Misconfiguration-Scanner
    matchers:
      - type: word
        words:
          - "database_url"
          - "secret_key"
        condition: or
